### ISSUE TITLE
No dirty version available

### ISSUE THREAD

**Issue by mdippery** [alexgenaud/Poetic-License#3]
My uncle was unable to apply the terms of this license to his software because there is no dirty limerick version available. The Poetic License should also come in a dirty form for all the uncles of the world.

**Comment by alexgenaud** [comment]
You sir, are a philosopher with vision! I shall warn that the software will most likely #@& your m*+#3r if not #@& the hard drive as well. Could you settle for innocent dirty grammar? This work 'as is' be provided, no warranty express or implieded ... ?

**Comment by alexgenaud** [comment]
Implemented one four letter word. May it be naughty enough for the venerable dirty uncles of the world.

**Comment by waldyrious** [comment]
> Implemented one four letter word.

For future reference (let me know if these notes are unwelcome, @alexgenaud!), this was done in commit 19a22f0bd6fd608bc1f4e8426c80fc3cd2f92118.
